query UserFamilies($email: String!) {
  user {
    id
    name
    ownedFamilies {
      id
    }
    families(orderBy: name_ASC) {
      id
      name
      kids(orderBy: name_ASC) {
        id
        name
        kredits
      }
    }
  }
  allInvitations(filter: {email: $email}) {
    id
    family {
      id
      name
      owner {
        name
      }
    }
  }
}
